server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/os/ {
        rewrite ^/api/os/(.*) /$1 break;
        proxy_pass http://hybrid-search-single:9200;
        proxy_set_header Host $host;
    }
}
