apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: template-job
spec:
  backoffLimit: {{ .Values.backoffLimit }}
  template:
    spec:
      containers:
        - name: template
          image: hybrid-search-template
          env:
            - name: ES_URL
              value: {{ .Values.esUrl }}
      restartPolicy: Never
