apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: seed-job
spec:
  backoffLimit: {{ .Values.backoffLimit }}
  template:
    spec:
      containers:
        - name: seeder
          image: hybrid-search-seed
          env:
            - name: ES_URL
              value: {{ .Values.esUrl }}
      restartPolicy: Never
