apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: {{ .Values.namespace }}
  labels:
    app: ui
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: nginx
          image: hybrid-search-ui
          ports:
            - containerPort: 80
